---
run:
  timeout: 3m
linters:
  enable:
  - asciicheck
  - bodyclose
  - bidichk
  - cyclop
  - depguard
  - dogsled
  - nilnil
  - tenv
  - dupl
  - durationcheck
  - errname
  - errorlint
  - exhaustive
  - exportloopref
  - forcetypeassert
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - gosec
  - importas
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - noctx
  - nolintlint
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - revive
  - rowserrcheck
  - sqlclosecheck
  - stylecheck
  - tagliatelle
  - testpackage
  - thelper
  - tparallel
  - unconvert
  - unparam
  - wastedassign
  - whitespace
  disable:
  - goerr113 # don't know how to make it ok in errors package
  - ireturn # maybe there's a better way for handling TfChecks
