---
linters:
  enable:
  - asciicheck
  - bodyclose
  - cyclop
  - whitespace
  - wastedassign
  - unparam
  - tparallel
  - thelper
  - tagliatelle
  - exportloopref
  - dupl
  - goconst
  - ifshort
  - importas
  - goimports
  - gofumpt
  - godot
  - gocritic
  - revive
  - depguard
  - dogsled
  - durationcheck
  - errname
  - errorlint
  - exhaustive
  - forbidigo
  - forcetypeassert
  - funlen
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - gocyclo
  - godox
  - goerr113
  - gofmt
  - goheader
  - gomnd
  - gomoddirectives
  - gomodguard
  - goprintffuncname
  - makezero
  - misspell
  - nakedret
  - nestif
  - nilerr
  - noctx
  - gosec
  - nolintlint
  - paralleltest
  - prealloc
  - predeclared
  - promlinter
  - rowserrcheck
  - sqlclosecheck
  - stylecheck
  - testpackage
  - unconvert
