---
builds:
  - binary: terraform-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=static
    ldflags:
      - -s
      - -w

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/terraform-tools/terraform-checker:{{ .Version }}"

snapshot:
  name_template: "{{ .FullCommit }}-SNAPSHOT"

release:
  github:
    owner: terraform-tools
    name: terraform-checker

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false
